version: 2
jobs:
  build:
    docker:
      - image: circleci/node:10-browsers

    working_directory: ~/repo

    steps:
      - checkout

      - run:
          name: Install
          command: yarn install

      - run:
          name: Selenium
          background: true
          command: |
            yarn run webdriver:update
            yarn run webdriver:start

      - run:
          name: run test
          command: |
            yarn test

