version: 2
jobs:
  build:
    docker:
      - image: circleci/node:10-browsers

    working_directory: ~/repo

    steps:
      - checkout

      - restore_cache:
          key: dependency-cache-{{ checksum "package.json" }}

      - run:
          name: Install
          command: yarn install

      - save_cache:
          key: dependency-cache-{{ checksum "package.json" }}
          paths:
            - node_modules

      - run:
          name: Selenium
          command: |
            yarn run webdriver:update

      - run:
          name: Selenium
          command: |
            yarn run webdriver:start
          background: true

  deploy:
    machine:
      enabled: true
    steps:
      - run: yarn test

workflows:
  version: 2
  build-and-test:
    jobs:
      - build
      - deploy:
          requires:
            - build
