version: 2
jobs:
  build:
    docker:
      - image: circleci/node:7.10

    working_directory: ~/repo

    steps:
      - checkout

      - run:
          name: Install Dependencies
          command: |
            sudo apt-get update
            sudo apt-get install python-pip tcpdump
            # Have to update firefox, default is ESR.
            sudo pip install --upgrade pip
            sudo pip install mozdownload mozinstall
            mozdownload --version latest --destination firefox.tar.bz2
            mozinstall firefox.tar.bz2
            sudo mkdir -p /opt/firefox/
            sudo cp -R firefox/* /opt/firefox/
            # Latest chrome is already installed in the default container.
            # curl -L -o google-chrome.deb https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
            # sudo dpkg -i google-chrome.deb
            # sudo sed -i 's|HERE/chrome\"|HERE/chrome\" --disable-setuid-sandbox|g' /opt/google/chrome/google-chrome
            # rm google-chrome.deb

      - run:
          name: Install
          command: yarn install

      - run:
          name: Selenium
          background: true
          command: |
            yarn run webdriver:update
            yarn run webdriver:start

      - run:
          name: run test
          command: |
            yarn test

workflows:
  version: 2
  test:
    jobs:
      - build
